### ISSUE TITLE
Ruby 3.0.0 +  Rails 6.1.1

### ISSUE THREAD

**Issue by ShadowMyst** [mul53/activestorage-ipfs#9]
wow I was very curious to find this Rails gem, I would like to know if you would have problems using it in Ruby 3.0 with Rails 6.1.1, since I'm starting to use them as an experiment.

Anyway, I've just created a fork in case I have problems and see if I can use it. I really liked this gem

**Comment by mul53** [comment]
@ShadowMyst should work fine, let me know if you encounter any challenges

**Comment by ShadowMyst** [comment]
So far it works great. What I did is that as in Rails 6.1.1 already in the javascript folder in the applicaction.js file they already use "import" instead of "require" I modified it this way:

```
import * as ActiveStorageIPFS from "activestorage-ipfs-js"
ActiveStorageIPFS.start()
```
![image](https://user-images.githubusercontent.com/16523482/105112602-040e5680-5a89-11eb-9e9b-33f765a42c36.png)

I only did it to keep the ES6 and that everything was with "import" 

I will continue to test it with my project, if I find an error I will be reporting it here

P.S.: I'm writing English in a translator, an excuse if it's badly written
